### PR TITLE
Return response on post

### PR DESCRIPTION
**Pull request by osahyoun**
I can't do anything meaningful without having access to ShareProgress' response.

Quite a lot of the test are already red, so not sure how this is going to affect existing specs.

### CODE REVIEW

**Comment by EricBoersma** [comment]
So, I run into a problem with this, specifically:

It works when `save` is successful, but when it fails, it's returning the same thing (both return `{"facebook"=>[], "email"=>[], "twitter"=>[]}`).

Since it doesn't throw errors on failure, it creates an inconsistent API. 

Also, I'm only seeing 2 failing tests. What are you seeing?

**Comment by osahyoun** [comment]
That's good news you're only seeing a pair of failing tests. I've a load, so it's a problem my end. 

I'm not sure what solution's best, but I do need to get back the ID of the created button. Perhaps you can raise if there's an error?

**Comment by osahyoun** [comment]
Ah, I see what's going on - the button object is re populated, so it should have the ID!

**Comment by EricBoersma** [comment]
Yep, if the save was successful, it should populate the info for you. The only thing that's not currently working is `variant` repopulation, because that's tricky and I don't think important enough to try to solve right now. If you do need to update the variants (with their IDs) the best bet is to grab the button all over from the API using its saved ID.

**Comment by osahyoun** [comment]
I'll need the variant IDs, so getting my hands on the raw response would be handy. Are you ok if I attach the response to the button object, perhaps:

``` ruby
button.save
# true

 button.response
 # {some: :data}

```

**Comment by NealJMD** [comment]
@osahyoun I think that sounds like a fine plan, but it seems to me like it would be better to bind the information you actually want to the Button object in the parser in the gem.  What are you actually unable to fetch from the button object after `update_attributes` is called in save?

**Comment by osahyoun** [comment]
@NealJMD ( @EricBoersma ) I wanted access to created variants, but I think I misread Eric's last comment, because `button.variants` already exists! Closing this PR. Thanks!

**Pull request closed without merging**
